name: sample_statistics

description: Sample statistics, histograms, probability distributions, and
  random sample generators for Dart.

version: 0.1.3

homepage: https://github.com/simphotonics/sample_statistics

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  exception_templates: ^0.2.4
  lazy_memo: ^0.1.7
  list_operators: ^0.4.3
  simulated_annealing: ^0.3.8

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1

# dependency_overrides:
#   simulated_annealing:
#     path: ../simulated_annealing/
