name: sample_statistics

description: Sample statistics, histograms, probability distributions, and
  random sample generators.

version: 1.0.0

homepage: https://github.com/simphotonics/sample_statistics

environment:
  sdk: '^3.13.0'

topics:
  - statistics
  - histogram
  - probability-distribution
  - random-sample-generator

dependencies:
  ansi_modifier: ^1.1.1
  exception_templates: ^1.1.0
  lazy_memo: ^2.0.0
  list_operators: ^1.0.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.32.0
