name: sample_statistics

description: A Dart library for calculating sample statistics and
             creating histograms. Includes common probability
             distribution functions and random sample generators.


version: 0.0.7-nullsafety

homepage: https://github.com/simphotonics/sample_statistics

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  exception_templates: ^0.1.1-nullsafety
  lazy_memo: ^0.0.3-nullsafety

dev_dependencies:
  minimal_test: ^0.1.2-nullsafety
  pedantic: ^1.9.2
