name: statistics

description: A Dart library for calculating statistics numeric samples and
             creating/exporting histograms. Includes common probability
             distribution functions and a simple random sample generator.


version: 0.0.1-nullsafety

homepage: https://github.com/simphotonics/statistics

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  exception_templates: ^0.1.1-nullsafety
  lazy_memo: ^0.0.2-nullsafety

dev_dependencies:
  minimal_test: ^0.1.2-nullsafety
  pedantic: ^1.9.2
