name: sample_statistics

description: Sample statistics, histograms, probability distributions, and
  random sample generators for Dart.

version: 0.2.2

homepage: https://github.com/simphotonics/sample_statistics

environment:
  sdk: '^3.9.0'

topics:
  - statistic
  - histogram
  - probability-distribution
  - random-sample-generator

dependencies:
  exception_templates: ^0.3.2
  lazy_memo: ^0.2.5
  list_operators: ^0.5.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
